[gyjd.job]
name = "simple_app"
description = "A simple app that does nothing"
script = "simple_app.py"
python_version = "3.11"
dependencies = ["gyjd>0.1.0dev10", "requests<3"]
tags = ["simple", "app"]

[gyjd.job.schedule.cron.default]
expression = "0 0 * * *"
timezone = "UTC"
